export class ObjectConfig {
    constructor(){
        this.enemies = [
          "ghost",
          "medusa",
          "troll",
          "lava_monster",
          "dragon"
        ],
        this.objects = [
          ["mushrooms", "fountain", "over_grass_flower1", "banana", "lollypop", "ogre"],
          ["arrow", "ruby", "apple", "burger", "cupcake", "ogre"],
          ["jewel", "sapphire", "cake", "cherries", "milk", "ogre"],
          ["Chest2_closed", "key", "cookie", "donut", "popsicle", "sundae"],
          ["Chest1_closed", "key", "grapes", "icecream", "pizza"]
        ];
        this.objectsNoLimit = [
          ["mushrooms", "over_grass_flower1", "banana", "lollypop"],
          ["arrow", "ruby", "apple", "burger", "cupcake"],
          ["jewel", "sapphire", "cake", "cherries", "milk"],
          ["cookie", "donut", "popsicle", "sundae"],
          ["grapes", "icecream", "pizza"]
        ];
        // the max number of objects w index 0 corresponding to the number of enemies
        this.frequencies = {
           key: 2,
           ghost: 3,
           medusa: 4,
           fountain: 4,
           troll: 3,
           lava_monster: 3,
           dragon: 3, 
           ogre: 3,
           Chest1_closed: 4,
           Chest2_closed: 4
        }
         this.heights = {
            Chest1_closed: 0,
            Chest2_closed: 0,
            fountain: 0,
            over_grass_flower1: -1 / 2,
            Rock_1: -1 / 2,
            Rock_2: -1 / 2,
            flag: 0,
            lever: 0,
            jewel: 0,
            key: 0,
            coin: 0,
            ruby: 0,
            apple: 0,
            sapphire: 0,
            cupcake: 0,
            ogre : 0,
            ghost : 0,
            medusa : 0,
            troll : 0,
            lava_monster : 1/4,
            dragon: 0,
            mushrooms: 0,
            arrow: 0,
            banana: 0,
            lollypop: 0,
            burger: 0,
            cake: 0,
            cherries: 0, 
            milk: 0, 
            cookie: 0, 
            donut: 0, 
            popsicle: 0,
            sundae: 0,
            grapes: 0,
            icecream: 0,
            pizza: 0
          };
           this.audio = {
            Chest1_closed: "knock",
            Chest2_closed: "knock",
            fountain: "waterfall",
            over_grass_flower1: "ding",
            Rock_1: "thump",
            Rock_2: "thump",
            flag: "thump",
            lever: "thump",
            jewel: "jewel",
            key: "ding",
            coin: "cha_ching",
            ruby: "jewel",
            sapphire: "jewel",
            dragon: "dragon_roar",
            cupcake: "yum",
            apple: "bite",
            ogre: "timpani_failure",
            ghost: "ghost",
            medusa : "timpani_failure",
            troll : "timpani_failure",
            lava_monster : "timpani_failure",
            mushrooms: "slurp",
            arrow: "timpani_failure",
            banana: "drink",
            lollypop: "lick",
            burger: "bite",
            cake: "bite",
            cherries: "bite", 
            milk: "drink", 
            cookie: "bite", 
            donut: "bite", 
            popsicle: "lick",
            sundae: "lick",
            grapes: "bite",
            icecream: "lick",
            pizza: "bite"
          };
           this.descriptions = {
            Chest1_closed: "red chest",
            Chest2_closed: "green chest",
            fountain: "fountain",
            over_grass_flower1: "flower",
            Rock_1: "rock",
            Rock_2: "rock",
            flag: "flag",
            lever: "lever",
            jewel: "jewel",
            key: "key",
            coin: "coin",
            apple: "apple",
            ruby: "ruby",
            sapphire: "sapphire",
            dragon: "dragon",
            cupcake: "cupcake",
            ogre: "ogre",
            ghost: "ghost",
            medusa : "medusa",
            troll : "troll",
            lava_monster : "lava_monster",
            mushrooms: "mushrooms",
            arrow: "arrow",
            banana: "banana",
            lollypop: "lollypop",
            burger: "burger",
            cake: "cake",
            cherries: "cherries", 
            milk: "milk", 
            cookie: "cookie", 
            donut: "donut", 
            popsicle: "popsicle",
            sundae: "sundae",
            grapes: "grapes",
            icecream: "icecream",
            pizza: "pizza"
          };
          this.animations = {
            
          };
          this.power = {
            Chest1_closed: 15,
            Chest2_closed: 15,
            fountain: 15,
            over_grass_flower1: 2,
            Rock_1: 1,
            Rock_2: 1,
            flag: 3,
            lever: 2,
            jewel: 10,
            key: 15,
            coin: 15,
            ruby: 10,
            sapphire: 10,
            apple: 10,
            dragon: -60,
            cupcake: 12,
            ogre: -5,
            ghost: -20,
            medusa: -30,
            troll: -40,
            lava_monster: -50,
            mushrooms: 15,
            arrow: 20,
            banana: 10,
            lollypop: 5,
            burger: 15,
            cake: 10,
            cherries: 15, 
            milk: 20, 
            cookie: 20, 
            donut: 25, 
            popsicle: 30,
            sundae: 30,
            grapes: 15,
            icecream: 30,
            pizza: 25
          };
          this.isCollectible = {
            Chest1_closed: false,
            Chest2_closed: false,
            fountain: false,
            over_grass_flower1: true,
            Rock_1: false,
            Rock_2: false,
            flag: false,
            lever: false,
            jewel: true,
            key: true,
            coin: true,
            ruby: true,
            sapphire: true,
            dragon: false,
            apple: false,
            cupcake: true,
            ogre: false,
            ghost: false,
            medusa: false,
            troll: false,
            lava_monster: false,
            mushrooms: true,
            arrow: true,
            banana: true,
lollypop: true,
burger: true,
cake: true,
cherries: true, 
milk: true, 
cookie: true, 
donut: true, 
popsicle: true,
sundae: true,
grapes: true,
icecream: true,
pizza: true
          }
          this.isAnimated = {
            Chest1_closed: false,
            Chest2_closed: false,
            fountain: false,
            over_grass_flower1: false,
            Rock_1: false,
            Rock_2: false,
            flag: false,
            lever: false,
            jewel: false,
            key: false,
            coin: true,
            ruby: false,
            sapphire: false,
            dragon: true,
            cupcake: false,
            ogre: true,
            ghost: true,
            lava_monster: true,
            apple: false,
            medusa: true,
            troll: true,
            mushrooms: false,
            arrow: false,
            banana: false,
lollypop: false,
burger: false,
cake: false,
cherries: false, 
milk: false, 
cookie: false, 
donut: false, 
popsicle: false,
sundae: false,
grapes: false,
icecream: false,
pizza: false
          }
    }
}